name: Give
version: 0.3
main: net.madmanmarkau.Give.Give
author: MadManMarkAu
description: >
             Command to give items to player.
commands:
  give_give:
    description: Gives user items.
    aliases: give
    usage: /<command> <item> [<amount>]
